import type { CallStatus } from '@/lib/store/call.store'

/** Call tones in `public/sounds/` (generated by apps/client/tool/gen_call_tones.py). */
export type Tone = 'ringtone' | 'ringback'

let audio: HTMLAudioElement | null = null
let current: Tone | null = null

/** Loop `tone` until stopTone() or another tone. No-op if it already plays. */
export function playTone(tone: Tone): void {
  if (current === tone) return
  stopTone()
  const a = new Audio(`/sounds/${tone}.wav`)
  a.loop = true
  audio = a
  current = tone
  a.play().catch(() => {
    // Autoplay is blocked until the user has interacted with the page; the
    // on-screen prompt (and the OS notification when hidden) still shows.
  })
}

export function stopTone(): void {
  audio?.pause()
  audio = null
  current = null
}

/** Which tone the current call state calls for. */
export function toneFor(status: CallStatus, incomingGroupRing: boolean): Tone | null {
  if (status === 'incoming') return 'ringtone'
  if (status === 'outgoing') return 'ringback'
  if (status === 'idle' && incomingGroupRing) return 'ringtone'
  return null
}
