services:
  auth-service:
    build:
      context: ../..
      dockerfile: apps/server/auth-service/Dockerfile
    env_file:
      - ../../apps/server/auth-service/.env
    environment:
      - CI=true
    command: >
      sh -lc "corepack enable &&
      pnpm config set only-built-dependencies-all true &&
      pnpm install --no-frozen-lockfile &&
      pnpm --filter @platform/auth-service start:dev"
    working_dir: /app
    volumes:
      - ../..:/app
      - /app/node_modules
    ports:
      - "3001:3001"
    depends_on:
      mongo:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks: [app-net]
