services:
  auth-service:
    build:
      context: ../..
      dockerfile: apps/server/auth-service/Dockerfile
    env_file:
      - ../../apps/server/auth-service/.env
    environment:
      - CI=true
      - NODE_ENV=production
    command: node dist/main.js
    ports:
      - "3001:3001"
    restart: always
    depends_on:
      mongo:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks: [app-net]
