// Builds the localized `texts` bag passed to <ProfileForm>. Extracted from
// app/(main)/profile/edit/page.tsx to keep the page under the 400-line limit;
// the produced object is identical to the inline literal.
export function buildProfileFormTexts(t: (key: string) => string) {
  return {
    displayNameLabel: t('displayNameLabel'),
    displayNamePlaceholder: t('displayNamePlaceholder'),
    bioLabel: t('bioLabel'),
    bioPlaceholder: t('bioPlaceholder'),
    dobLabel: t('dobLabel'),
    dobPlaceholder: t('dobPlaceholder'),
    phoneLabel: t('phoneLabel'),
    phonePlaceholder: t('phonePlaceholder'),
    phoneSendOtp: t('phoneSendOtp'),
    phoneSending: t('phoneSending'),
    phoneVerified: t('phoneVerified'),
    phoneUnverified: t('phoneUnverified'),
    phoneChange: t('phoneChange'),
    phoneOtpTitle: t('phoneOtpTitle'),
    phoneOtpSubtitle: t('phoneOtpSubtitle'),
    phoneOtpConfirm: t('phoneOtpConfirm'),
    phoneVerifying: t('phoneVerifying'),
    phoneOtpIncomplete: t('phoneOtpIncomplete'),
    phoneResend: t('phoneResend'),
    phoneResendCountdown: t('phoneResendCountdown'),
    phoneSuccess: t('phoneSuccess'),
    phoneErrorInvalid: t('phoneErrorInvalid'),
    phoneErrorSend: t('phoneErrorSend'),
    phoneErrorVerify: t('phoneErrorVerify'),
    phoneErrorExpired: t('phoneErrorExpired'),
    phoneErrorTaken: t('phoneErrorTaken'),
    phoneNoticeText: t('phoneNoticeText'),
    phoneVerifyAction: t('phoneVerifyAction'),
    phoneModalPhoneTitle: t('phoneModalPhoneTitle'),
    phoneModalPhoneSubtitle: t('phoneModalPhoneSubtitle'),
    phoneErrorRateLimit: t('phoneErrorRateLimit'),
    genderLabel: t('genderLabel'),
    genderPlaceholder: t('genderPlaceholder'),
    genderMale: t('genderMale'),
    genderFemale: t('genderFemale'),
    genderOther: t('genderOther'),
    privacySectionLabel: t('privacySectionLabel'),
    privacySectionHint: t('privacySectionHint'),
    showDobLabel: t('showDobLabel'),
    showPhoneLabel: t('showPhoneLabel'),
    showGenderLabel: t('showGenderLabel'),
    emailLabel: t('emailLabel'),
    saveButton: t('saveButton'),
  }
}
