// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8q9vgMzZYEPqEYcT1nRPb2JrWmd3XXwI',
    appId: '1:246431845875:web:246c24ecc32054f798d686',
    messagingSenderId: '246431845875',
    projectId: 'pon-c30fd',
    authDomain: 'pon-c30fd.firebaseapp.com',
    storageBucket: 'pon-c30fd.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3PPzuSOYuzBNrGERZg5LKOc_gt8CLIas',
    appId: '1:246431845875:android:9d2986a5e8e527a798d686',
    messagingSenderId: '246431845875',
    projectId: 'pon-c30fd',
    storageBucket: 'pon-c30fd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpWX5jbhLJH1_ShH1FQd1BZcchi9Y_kDs',
    appId: '1:246431845875:ios:42c8aa99eb0ce81298d686',
    messagingSenderId: '246431845875',
    projectId: 'pon-c30fd',
    storageBucket: 'pon-c30fd.firebasestorage.app',
    iosBundleId: 'com.platform.platformClient',
  );

}