// ── Auth DTOs — single source of truth from the auth-service OpenAPI spec ────
// Generated by `pnpm gen:api-types` (openapi-typescript) into
// `lib/api/generated/auth-api.ts` from `apps/server/auth-service/openapi.json`.
// To refresh after the auth-service contract changes, re-run `pnpm gen:api-types`.
//
// These re-exports give the auth request DTOs a real contract-derived type so
// the hand-written client in `lib/api/auth.ts` stays in sync with the backend.
// chat-service has no OpenAPI spec (Spring, springdoc not added) so its types
// (Message, Conversation, …) below remain hand-written — expected/out of scope.
import type { components as AuthApiComponents } from './generated/auth-api'

export type AuthSchemas = AuthApiComponents['schemas']

/** `POST /auth/login` request body (email, password). */
export type LoginRequest = AuthSchemas['LoginDto']
/** `POST /auth/register` request body (email, password, displayName). */
export type RegisterRequest = AuthSchemas['RegisterDto']
/** `POST /auth/refresh` request body (sid, refreshToken). */
export type RefreshRequest = AuthSchemas['RefreshDto']
/** `POST /auth/verify-otp` request body (email, otp). */
export type VerifyOtpRequest = AuthSchemas['VerifyOtpDto']

export interface Reaction {
  userId: string
  emoji: string
}

export interface PinnedMessage {
  id: string
  senderId: string
  content: string
  createdAt: string
  type?: string
}

export interface Conversation {
  id: string
  participants: string[]
  type: 'direct' | 'group'
  name: string | null
  avatarUrl: string | null
  wallpaper: string | null
  admins: string[]
  createdBy: string
  isPublic: boolean
  status: 'pending' | 'accepted'
  isMuted: boolean
  /** epoch ms; 9_200_000_000_000_000 = muted forever; null = not muted */
  muteExpiresAt?: number | null
  isArchived: boolean
  /** true when this conversation has been moved to the Blocked section by the current user */
  isBlocked?: boolean
  pinnedMessages: PinnedMessage[]
  autoDeleteSeconds: number | null
  lastMessage: {
    content: string
    senderId: string
    createdAt: string
  } | null
  lastMessageAt: string | null
  unreadCount: number
}

export type MessageType =
  | 'text' | 'image' | 'video' | 'file' | 'voice' | 'sticker' | 'system' | 'call_log' | 'ai'
  | 'meeting_summary'

/** Parsed `content` of a `meeting_summary` message (Track A contract §6). */
export interface MeetingSummaryPayload {
  attendees: string[]
  durationSec: number
  overview: string
  keyPoints: string[]
  actionItems: string[]
}

export interface UploadResult {
  url: string
  filename: string
  size: number
}

export interface LinkPreview {
  url: string
  title?: string | null
  description?: string | null
  image?: string | null
  siteName?: string | null
}

/**
 * A single RAG citation source cited by an AI answer. Delivered on the
 * `AI_STREAM_DONE` STOMP event as `{ documentId, fileName, score }` and then
 * attached to the persisted AI `Message` in the cache so the bubble can render
 * clickable source chips. `fileName` may be empty for older payloads.
 */
export interface AiSource {
  documentId: string
  fileName: string
  score: number
  /** Present only for web-search sources — the external page URL. When set,
   * the chip opens this URL in a new tab instead of the conversation KB view. */
  url?: string
  /** Source origin. Defaults to 'kb' when absent (backward compatible). */
  type?: 'kb' | 'web'
}

export interface Message {
  id: string
  conversationId: string
  senderId: string
  senderName?: string
  content: string
  type: MessageType
  createdAt: string
  editedAt?: string
  replyToId?: string
  replyPreview?: {
    messageId: string
    senderId: string
    content: string
  }
  recalled?: boolean
  reactions?: Reaction[]
  deletedFor?: string[]
  readBy?: string[]
  /** RAG citation sources, attached from the AI_STREAM_DONE event (AI messages only). */
  sources?: AiSource[]
}

/**
 * A `senderId` starting with `extbot:` identifies a Bot Factory personal
 * assistant bot — rendered with its own identity, distinct from the native
 * `@AI` bot and from human senders.
 */
export const isExternalBot = (senderId: string) => senderId.startsWith('extbot:')

export interface MessagesResponse {
  content: Message[]
  page: number
  size: number
  totalElements: number
  hasNext: boolean
}

export interface ConversationsResponse {
  content: Conversation[]
  page: number
  size: number
  totalElements: number
}

export interface UserSearchResult {
  _id?: string
  id?: string
  email: string
  displayName: string
  avatarUrl: string | null
  bio?: string
  isVerified?: boolean
  /** Only present when the user was matched by exact phone number. */
  phoneNumber?: string
  /** How this result was matched. 'phone' results carry phoneNumber. */
  matchedBy?: 'phone' | 'name_email'
}

/** Response shape of `GET /api/users/search`. */
export interface UserSearchResponse {
  results: UserSearchResult[]
  matchedBy: 'phone' | 'name_email'
}

export interface UserStatus {
  userId: string
  online: boolean
  lastSeen: string | null
}

export interface AiTraceResponse {
  messageId: string
  inputTokens: number
  outputTokens: number
  thinkingBlocks?: string[]
  toolCalls?: Array<{ name: string; input: unknown; output: unknown }>
  ragSources?: Array<{ documentId: string; excerpt: string; score: number }>
  promptVariables?: Record<string, string>
}

/** Thumbs feedback rating on an AI answer (`none` clears a prior vote). */
export type FeedbackRating = 'up' | 'down' | 'none'

/** `POST /api/messages/{id}/feedback` response. */
export interface MessageFeedbackResult {
  rating: FeedbackRating
  comment?: string
}

export interface PageResponse<T> {
  content: T[]
  page: number
  size: number
  totalElements: number
}

// STOMP event shapes (broadcasted on /topic/conversation/{id})
export type StompEvent =
  | { type: 'MESSAGE_UPDATED'; messageId: string; conversationId: string; content: string; editedAt: string }
  | { type: 'MESSAGE_RECALLED'; messageId: string; conversationId: string }
  | { type: 'MESSAGE_READ'; messageId: string; readerId: string }
  | { type: 'REACTION_UPDATED'; messageId: string; reactions: Reaction[] }
  | { type: 'PINNED_MESSAGE'; conversationId: string; messageId: string; pinnedMessages: string[] }
  | { type: 'CONVERSATION_UPDATED'; conversation: Conversation }
  | { type: 'AI_STREAM_CHUNK'; chunk: string; senderId: string; conversationId: string }
  | { type: 'AI_STREAM_DONE'; senderId: string; conversationId: string; sources?: AiSource[] }
  | { type: 'AI_STREAM_ERROR'; error: string; code?: string; senderId: string; conversationId: string }
  | { type: 'AI_TOOL_CALL'; toolName: string; inputSummary: string; sensitive?: boolean; senderId: string; conversationId: string }
  | { type: 'KB_STATUS_UPDATE'; documentId: string; status: 'pending' | 'processing' | 'done' | 'error'; chunkCount?: number }

// ── Group call (Track A contract §3) ────────────────────────────────────────

export type CallMedia = 'audio' | 'video'

/** A participant in a CallSession roster. */
export interface CallParticipant {
  userId: string
  displayName: string
  joinedAt?: string
  leftAt?: string | null
}

/**
 * Per-conversation call lifecycle events broadcast on
 * `/topic/conversation/{id}` (distinct from per-message StompEvents).
 */
export type CallEvent =
  | {
      event: 'call.started'
      callId: string
      conversationId: string
      media: CallMedia
      aiNotetaker: boolean
      startedBy: string
      startedByName: string
      participants: CallParticipant[]
    }
  | { event: 'call.roster'; callId: string; participants: CallParticipant[] }
  | { event: 'call.ended'; callId: string }

// Live state of the AI assistant's in-progress reply, shown as a streaming
// bubble (parity with Flutter StreamingAiBubble): "thinking" dots before the
// first chunk, active tool indicator, then streamed text with a blinking cursor.
export interface AiStreamState {
  content: string
  thinking: boolean
  activeTools: string[]
  /** Names of active tools flagged sensitive (state-changing / outbound). */
  sensitiveTools: string[]
}

// ── Admin usage & quality dashboard (TASK-13) ───────────────────────────────
// Mirror of ai-service `GET /usage/dashboard` (port 3002, gated by
// MANAGE_WORKSPACE). Single source of truth for the web admin dashboard.

/** The date window the dashboard covers. */
export interface UsageRange {
  /** Inclusive start, `YYYY-MM-DD`. */
  from: string
  /** Inclusive end, `YYYY-MM-DD`. */
  to: string
  /** Human label — `YYYY-MM` for a month window, else a range string. */
  label: string
}

/** Headline totals. `estimatedCostUsd` = sum of `perModelCost[].costUsd`. */
export interface UsageTotals {
  inputTokens: number
  outputTokens: number
  /** Authoritative volume figure (from token_usage rollup). */
  totalTokens: number
  requestCount: number
  /** Model-aware estimate; derived from messages.trace, may differ from token totals. */
  estimatedCostUsd: number
}

/** One point in the over-time series (token_usage rollup, zero-filled gaps). */
export interface UsageDailyPoint {
  date: string
  inputTokens: number
  outputTokens: number
  totalTokens: number
  requestCount: number
}

/** Per-model cost breakdown (messages.trace grouped by model). */
export interface UsagePerModelCost {
  model: string
  inputTokens: number
  outputTokens: number
  requestCount: number
  /** Resolved from the ai-service price map (echoed for transparency). */
  inputPricePerMTok: number
  outputPricePerMTok: number
  /** round(2). */
  costUsd: number
}

/** A top consumer by tokens (token_usage grouped by user, desc). */
export interface UsageTopUser {
  userId: string
  /** Best-effort users-collection join; falls back to userId. */
  displayName: string
  totalTokens: number
  requestCount: number
  estimatedCostUsd: number
}

/** A recent 👎-rated answer in the window. */
export interface UsageWorstAnswer {
  messageId: string
  conversationId: string
  /** Optional reviewer comment. */
  comment: string | null
  /** First ~200 chars of the AI answer. */
  answerPreview: string
  /** Null when the underlying message has no timestamp. */
  createdAt: string | null
}

/** Feedback rollup for the window. */
export interface UsageFeedback {
  up: number
  down: number
  /** Rated messages with a non-cleared vote in window. */
  total: number
  /** down / total, 0..1; 0 when total === 0. */
  thumbsDownRate: number
  /** Most recent down-rated answers, limit 10. */
  worstAnswers: UsageWorstAnswer[]
}

/** `GET /usage/dashboard` response. */
export interface DashboardResponse {
  range: UsageRange
  totals: UsageTotals
  daily: UsageDailyPoint[]
  perModelCost: UsagePerModelCost[]
  topUsers: UsageTopUser[]
  feedback: UsageFeedback
}
