// ── Auth DTOs — single source of truth from the auth-service OpenAPI spec ────
// Generated by `pnpm gen:api-types` (openapi-typescript) into
// `lib/api/generated/auth-api.ts` from `apps/server/auth-service/openapi.json`.
// To refresh after the auth-service contract changes, re-run `pnpm gen:api-types`.
//
// These re-exports give the auth request DTOs a real contract-derived type so
// the hand-written client in `lib/api/auth.ts` stays in sync with the backend.
// chat-service has no OpenAPI spec (Spring, springdoc not added) so its types
// (Message, Conversation, …) below remain hand-written — expected/out of scope.
import type { components as AuthApiComponents } from './generated/auth-api'

export type AuthSchemas = AuthApiComponents['schemas']

/** `POST /auth/login` request body (email, password). */
export type LoginRequest = AuthSchemas['LoginDto']
/** `POST /auth/refresh` request body (sid, refreshToken). */
export type RefreshRequest = AuthSchemas['RefreshDto']
/** `POST /auth/verify-otp` request body (email, otp). */
export type VerifyOtpRequest = AuthSchemas['VerifyOtpDto']
/** `POST /api/users/me/change-password` body — `currentPassword` omitted when setting the first one. */
export type ChangePasswordRequest = AuthSchemas['ChangePasswordDto']

// ── Invitations (invite-only onboarding) ─────────────────────────────────────
/** `POST /auth/invitations/:token/accept-password` request body. */
export type AcceptInvitationRequest = AuthSchemas['AcceptInvitationPasswordDto']
/** `GET /auth/invitations/:token` response — public preview. `roleName` is null for a deleted role. */
export type InvitationPreview = AuthSchemas['InvitationPreviewDto']

// ── Two-factor authentication (TOTP) ─────────────────────────────────────────
// MfaChallenge, MfaEnroll*, MfaVerifyRequest, MfaBackupCodesResponse, … are
// aliases of the generated DTOs in `./mfa-types` (kept apart for the 400-line limit).
export type * from './mfa-types'

export interface Reaction {
  userId: string
  emoji: string
}

export interface PinnedMessage {
  id: string
  senderId: string
  content: string
  createdAt: string
  type?: string
}

export interface Conversation {
  id: string
  participants: string[]
  type: 'direct' | 'group'
  name: string | null
  avatarUrl: string | null
  wallpaper: string | null
  admins: string[]
  createdBy: string
  isPublic: boolean
  /** Set on department groups — they can never be public channels. */
  departmentId?: string | null
  status: 'pending' | 'accepted'
  isMuted: boolean
  /** epoch ms; 9_200_000_000_000_000 = muted forever; null = not muted */
  muteExpiresAt?: number | null
  isArchived: boolean
  /** true when this conversation has been moved to the Blocked section by the current user */
  isBlocked?: boolean
  /** userIds that have a pending invitation to this group (backend field) */
  pendingMembers?: string[]
  pinnedMessages: PinnedMessage[]
  autoDeleteSeconds: number | null
  /** When disappearing messages were last turned on (only newer messages expire). */
  autoDeleteEnabledAt?: string | null
  lastMessage: LastMessage | null
  lastMessageAt: string | null
  unreadCount: number
  createdAt?: string
}

/**
 * Conversation-list preview of the newest message. `messageId`/`type` are null on
 * previews written before they existed; `recalled === true` means the message was
 * unsent (`content` is blank) — render the localized "recalled" label instead.
 */
export interface LastMessage {
  content: string
  senderId: string
  createdAt: string
  messageId?: string | null
  type?: string | null
  recalled?: boolean
}

/**
 * Fields of a conversation that every member shares. The topic
 * `CONVERSATION_UPDATED` carries only these (never the viewer's own unread / mute /
 * archive / block state), so clients MERGE it into their per-user copy.
 */
export const SHARED_CONVERSATION_FIELDS = [
  'id', 'type', 'name', 'avatarUrl', 'participants', 'admins', 'createdBy',
  'autoDeleteSeconds', 'autoDeleteEnabledAt', 'lastMessage', 'lastMessageAt', 'createdAt',
  'status', 'isPublic', 'pinnedMessages', 'wallpaper', 'pendingMembers', 'departmentId',
] as const satisfies readonly (keyof Conversation)[]

export type MessageType =
  | 'text' | 'image' | 'video' | 'file' | 'voice' | 'sticker' | 'system' | 'call_log' | 'ai'
  | 'meeting_summary'

/** Parsed `content` of a `meeting_summary` message (Track A contract §6). */
export interface MeetingSummaryPayload {
  attendees: string[]
  durationSec: number
  overview: string
  keyPoints: string[]
  actionItems: string[]
}

export interface UploadResult {
  url: string
  filename: string
  size: number
}

export interface LinkPreview {
  url: string
  title?: string | null
  description?: string | null
  image?: string | null
  siteName?: string | null
}

/**
 * A single RAG citation source cited by an AI answer. Delivered on the
 * `AI_STREAM_DONE` STOMP event as `{ documentId, fileName, score }` and then
 * attached to the persisted AI `Message` in the cache so the bubble can render
 * clickable source chips. `fileName` may be empty for older payloads.
 */
export interface AiSource {
  documentId: string
  fileName: string
  score: number
  /** Present only for web-search sources — the external page URL. When set,
   * the chip opens this URL in a new tab instead of the conversation KB view. */
  url?: string
  /** Source origin. Defaults to 'kb' when absent (backward compatible). */
  type?: 'kb' | 'web'
}

export interface Message {
  id: string
  conversationId: string
  senderId: string
  senderName?: string
  content: string
  type: MessageType
  createdAt: string
  editedAt?: string
  replyToId?: string
  replyPreview?: {
    messageId: string
    senderId: string
    content: string
    /** The quoted message was unsent — `content` is blank, show the recalled label. */
    recalled?: boolean
  }
  recalled?: boolean
  reactions?: Reaction[]
  deletedFor?: string[]
  readBy?: string[]
  /** RAG citation sources, attached from the AI_STREAM_DONE event (AI messages only). */
  sources?: AiSource[]
  /** Sensitive AI actions awaiting confirmation (F2) — rendered by the confirmation card. */
  pendingActions?: AiPendingAction[]
  /** Persisted AI replies: the stream `replyId` this message came from (absent on others). */
  aiReplyId?: string
}

/**
 * A sensitive AI tool call waiting for the requester's confirmation (F2). Never
 * render `toolName` / `provider` raw — they are machine ids (`mcp__…`, `custom_<hex>`).
 */
export interface AiPendingAction {
  id: string
  toolName?: string
  provider?: string
  summary?: Record<string, unknown>
  status?: 'pending' | 'confirmed' | 'cancelled' | 'failed' | 'expired' | string
  expiresAt?: string
  requesterId?: string
}

/**
 * A `senderId` starting with `extbot:` identifies a Bot Factory personal
 * assistant bot — rendered with its own identity, distinct from the native
 * `@AI` bot and from human senders.
 */
export const isExternalBot = (senderId: string) => senderId.startsWith('extbot:')

export interface MessagesResponse {
  content: Message[]
  page: number
  size: number
  totalElements: number
  hasNext: boolean
}

export interface ConversationsResponse {
  content: Conversation[]
  page: number
  size: number
  totalElements: number
  hasNext?: boolean
}

export interface UserSearchResult {
  _id?: string
  id?: string
  email: string
  displayName: string
  avatarUrl: string | null
  bio?: string
  isVerified?: boolean
  /** Only present when the user was matched by exact phone number. */
  phoneNumber?: string
  /** How this result was matched. 'phone' results carry phoneNumber. */
  matchedBy?: 'phone' | 'name_email'
}

/** Response shape of `GET /api/users/search`. */
export interface UserSearchResponse {
  results: UserSearchResult[]
  matchedBy: 'phone' | 'name_email'
}

export interface UserStatus {
  userId: string
  online: boolean
  lastSeen: string | null
}

/**
 * One tool call of an AI reply (`GET /api/messages/{id}/trace`). `inputSummary`
 * is the start of the raw tool input (it can hold an email body) and
 * `resultSummary` the start of the raw tool output — neither is ever rendered.
 */
export interface AiTraceToolCall {
  toolName: string
  inputSummary?: string | null
  resultSummary?: string | null
}

/** `GET /api/messages/{id}/trace` — how the AI produced a reply. */
export interface AiTraceResponse {
  thinkingBlocks?: string[]
  toolCalls?: AiTraceToolCall[]
  /** TOTAL prompt tokens, cache reads and writes included. */
  inputTokens: number
  outputTokens: number
  thinkingTokens?: number
  processingMs?: number
  model?: string | null
  iterationCount?: number
  /** Prompt-cache reads — subset of `inputTokens`. */
  cachedInputTokens?: number
  /** Prompt-cache writes — subset of `inputTokens`. */
  cacheCreationInputTokens?: number
}

/** Thumbs feedback rating on an AI answer (`none` clears a prior vote). */
export type FeedbackRating = 'up' | 'down' | 'none'

/** `POST /api/messages/{id}/feedback` response. */
export interface MessageFeedbackResult {
  rating: FeedbackRating
  comment?: string
}

export interface PageResponse<T> {
  content: T[]
  page: number
  size: number
  totalElements: number
}

// STOMP event shapes (broadcasted on /topic/conversation/{id})
export type StompEvent =
  // `editedAt` is absent for pending-action status updates (they carry `pendingActions`).
  | {
      type: 'MESSAGE_UPDATED'
      messageId: string
      conversationId: string
      content?: string
      editedAt?: string
      pendingActions?: AiPendingAction[]
    }
  | { type: 'MESSAGE_RECALLED'; messageId: string; conversationId: string }
  | { type: 'MESSAGE_READ'; messageId: string; readerId: string }
  | { type: 'REACTION_UPDATED'; messageId: string; reactions: Reaction[] }
  | { type: 'PINNED_MESSAGE'; conversationId: string; messageId: string; pinnedMessages: string[] }
  | { type: 'CONVERSATION_UPDATED'; conversation: Conversation }
  | {
      type: 'AI_ACTION_PENDING'
      conversationId: string
      replyId?: string
      requesterId?: string
      action?: AiPendingAction
    }
  // Every AI stream frame names its reply (`replyId`) and who asked (`requesterId`).
  | {
      type: 'AI_STREAM_CHUNK'
      chunk: string
      senderId: string
      conversationId: string
      replyId?: string
      requesterId?: string
    }
  | {
      type: 'AI_STREAM_DONE'
      senderId: string
      conversationId: string
      sources?: AiSource[]
      pendingActions?: AiPendingAction[]
      replyId?: string
      requesterId?: string
    }
  | {
      type: 'AI_STREAM_ERROR'
      error: string
      code?: string
      stopReason?: string
      senderId: string
      conversationId: string
      replyId?: string
      requesterId?: string
    }
  | {
      type: 'AI_TOOL_CALL'
      toolName: string
      inputSummary: string
      sensitive?: boolean
      senderId: string
      conversationId: string
      replyId?: string
      requesterId?: string
    }
  | { type: 'KB_STATUS_UPDATE'; documentId: string; status: 'pending' | 'processing' | 'done' | 'error'; chunkCount?: number }

/** Per-user events delivered on `/user/queue/notifications`. */
export type UserQueueEvent =
  | {
      type: 'NEW_MESSAGE' | 'MENTIONED_YOU'
      conversationId: string
      senderId?: string
      senderName?: string
      content?: string
      messageType?: string
      /** Id + ISO time of the message — lets the list update the row in place. */
      messageId?: string
      createdAt?: string
    }
  /** Send rate exceeded — the message was dropped. */
  | { type: 'RATE_LIMITED' }
  /** `/app/chat.send` refused (code: chat-service ErrorCodes, `NOT_FOUND`, `FORBIDDEN`, `BAD_REQUEST`). */
  | { type: 'MESSAGE_REJECTED'; code?: string; conversationId?: string }
  /** The actor's FULL view after a per-user change (mute / archive / read / block …). */
  | { type: 'CONVERSATION_UPDATED'; conversation: Conversation }
  /** My role / departments / permissions changed — refresh the token silently. */
  | { type: 'CLAIMS_CHANGED' }

// ── Group call (Track A contract §3) ────────────────────────────────────────

export type CallMedia = 'audio' | 'video'

/** A participant in a CallSession roster. */
export interface CallParticipant {
  userId: string
  displayName: string
  joinedAt?: string
  leftAt?: string | null
}

/**
 * Per-conversation call lifecycle events broadcast on
 * `/topic/conversation/{id}` (distinct from per-message StompEvents).
 */
export type CallEvent =
  | {
      event: 'call.started'
      callId: string
      conversationId: string
      media: CallMedia
      aiNotetaker: boolean
      startedBy: string
      startedByName: string
      participants: CallParticipant[]
      /** Media path of this call (absent from older servers = mesh). */
      transport?: CallTransport
      /** 'direct' = 1-on-1 (Messenger-style UI), 'group' otherwise. */
      kind?: 'direct' | 'group'
      livekitUrl?: string | null
    }
  | { event: 'call.roster'; callId: string; participants: CallParticipant[] }
  | {
      event: 'call.ended'
      callId: string
      /** hangup | declined | busy | no_answer | media_error | failed (sfu only). */
      reason?: string
    }

// Live state of the AI assistant's in-progress reply, shown as a streaming
// bubble (parity with Flutter StreamingAiBubble): "thinking" dots before the
// first chunk, active tool indicator, then streamed text with a blinking cursor.
export interface AiStreamState {
  content: string
  thinking: boolean
  activeTools: string[]
  /** Names of active tools flagged sensitive (state-changing / outbound). */
  sensitiveTools: string[]
}

// Admin usage & quality dashboard types (TASK-13) live in ./usage-types.ts.
export * from './usage-types'

// ─── Calls on LiveKit (docs/api-spec.md "Calls on LiveKit") ───────────────────

/** Media path the server picks for a call. */
export type CallTransport = 'mesh' | 'sfu'

export interface CallConfig {
  transport: CallTransport
  livekitUrl?: string | null
}

export interface CallToken {
  url: string
  token: string
}
