#!/usr/bin/env bash
#
# One-shot local dev bring-up. Assumes Docker Desktop is already running.
#
#   ./scripts/dev/up.sh                 # start everything (build only if image missing)
#   ./scripts/dev/up.sh --build         # force-rebuild the 4 backend images first
#   ./scripts/dev/up.sh --seed          # (re)seed the fake test data
#   ./scripts/dev/up.sh --no-web        # backends only, don't start the Next.js dev server
#   ./scripts/dev/up.sh --phone         # run the Flutter app on a real phone over the LAN
#   ./scripts/dev/up.sh --flutter       # ...or on an iOS simulator (heavier on the Mac)
#
# Flags combine. Everything here is idempotent — safe to re-run.

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
COMPOSE="docker compose -f $ROOT/infra/docker-compose/compose.yml"
SIMULATOR="${PON_SIMULATOR:-iPhone 17 Pro}"

DO_BUILD=0 DO_SEED=0 DO_WEB=1 DO_FLUTTER=0 DO_PHONE=0
for arg in "$@"; do
  case "$arg" in
    --build)   DO_BUILD=1 ;;
    --seed)    DO_SEED=1 ;;
    --no-web)  DO_WEB=0 ;;
    --flutter) DO_FLUTTER=1 ;;
    --phone)   DO_PHONE=1 ;;
    -h|--help) sed -n '3,12p' "$0" | sed 's/^# \{0,1\}//'; exit 0 ;;
    *) echo "unknown flag: $arg (try --help)" >&2; exit 2 ;;
  esac
done

step() { printf '\n\033[1;36m▶ %s\033[0m\n' "$1"; }
ok()   { printf '  \033[32m✓\033[0m %s\n' "$1"; }
warn() { printf '  \033[33m!\033[0m %s\n' "$1"; }
die()  { printf '  \033[31m✗\033[0m %s\n' "$1" >&2; exit 1; }

# --------------------------------------------------------------- preflight
step "Preflight"
docker info >/dev/null 2>&1 || die "Docker isn't running — start Docker Desktop first."
ok "docker daemon up"

# Secrets are gitignored, so a fresh clone has none of these. Name the exact file
# and its template instead of letting compose start with empty vars and fail
# somewhere deep (chat-service boots but rejects every token, AI goes silent, …).
need_env() {
  [ -f "$ROOT/$1" ] && return 0
  printf '  \033[31m✗\033[0m missing %s\n' "$1" >&2
  printf '      cp %s %s   then fill it in (ask the repo owner for the values)\n' "$2" "$1" >&2
  return 1
}
missing=0
need_env "infra/docker-compose/.env" "infra/docker-compose/.env.example" || missing=1
need_env "apps/server/auth-service/.env" "apps/server/auth-service/.env.example" || missing=1
[ "$missing" = 0 ] || die "fill in the env file(s) above and re-run — see scripts/dev/README.md"
ok "env files present"

# Not a secret — just which host the browser talks to — so generate it rather
# than making every member copy it by hand. Next.js reads this ahead of
# .env.local, which holds only the env-independent values (Firebase). Backend
# URLs live per environment: this file for dev, .env.production for prod.
if [ ! -f "$ROOT/apps/web/.env.development.local" ]; then
  cat >"$ROOT/apps/web/.env.development.local" <<'WEBENV'
# Generated by scripts/dev/up.sh — points the web dev server at the local stack.
# Next.js loads this ahead of `.env.local`, so every other var (Firebase, …)
# still comes from there. Do not delete it while running the local stack: with
# no NEXT_PUBLIC_WS_URL the client opens a socket to the Next dev server, which
# never answers, and realtime dies silently (REST keeps working).
NEXT_PUBLIC_AUTH_URL=http://localhost:3001
NEXT_PUBLIC_CHAT_URL=http://localhost:8080
NEXT_PUBLIC_WS_URL=ws://localhost:8080/ws
NEXT_PUBLIC_AI_URL=http://localhost:3002
WEBENV
  ok "created apps/web/.env.development.local"
fi
[ -f "$ROOT/apps/web/.env.local" ] \
  || warn "apps/web/.env.local missing — web runs, but Firebase phone auth won't"
# Secrets that only sign or encrypt *local* data are generated per machine rather
# than copied from production. Reusing the production values means a token signed
# on this laptop is accepted by the live API, and this laptop can decrypt the
# production token vault — so the copy is the vulnerability, not the leak of it.
# Generated once and kept (gitignored), so local sessions survive a re-run.
DEV_SECRETS="$ROOT/infra/docker-compose/.env.dev-secrets"
if [ ! -f "$DEV_SECRETS" ]; then
  {
    echo "# Generated by scripts/dev/up.sh — random, per-machine, DEV ONLY."
    echo "# Never copy production secrets in here, and never copy these to production."
    echo "# Delete this file to roll new ones (every local session is invalidated)."
    echo "JWT_ACCESS_SECRET=$(openssl rand -hex 32)"
    echo "JWT_REFRESH_SECRET=$(openssl rand -hex 32)"
    echo "SESSION_SECRET=$(openssl rand -hex 32)"
    # aes-256-gcm: the key is base64-decoded and must be exactly 32 bytes.
    echo "CONNECTOR_VAULT_KEY=$(openssl rand -base64 32)"
    echo "INTERNAL_API_KEY=$(openssl rand -hex 24)"
  } >"$DEV_SECRETS"
  ok "generated dev-only secrets (infra/docker-compose/.env.dev-secrets)"
fi
set -a
# shellcheck disable=SC1090
. "$DEV_SECRETS"
set +a
[ -n "${JWT_ACCESS_SECRET:-}" ] || die "failed to load $DEV_SECRETS — delete it and re-run"
ok "dev secrets loaded (distinct from production by construction)"

# The Docker path gets these through compose. Running a service straight from
# source reads its own .env instead, so a leftover value there would sign tokens
# the containers reject — and if it is the production secret, tokens the
# production API accepts.
file_jwt="$(grep -E '^JWT_ACCESS_SECRET=' "$ROOT/apps/server/auth-service/.env" 2>/dev/null | head -1 | cut -d= -f2-)"
if [ -n "$file_jwt" ] && [ "$file_jwt" != "$JWT_ACCESS_SECRET" ]; then
  warn "apps/server/auth-service/.env has a different JWT_ACCESS_SECRET.
      Harmless for this Docker stack, but 'pnpm auth' from source would mint
      tokens the containers reject. To align it (and stop holding a production
      secret on this machine):
        sed -i '' 's|^JWT_ACCESS_SECRET=.*|JWT_ACCESS_SECRET=$JWT_ACCESS_SECRET|' apps/server/auth-service/.env"
fi

# ------------------------------------------------------------------ build
if [ "$DO_BUILD" = 1 ]; then
  step "Rebuilding backend images (Maven build for chat-service takes a few minutes)"
  $COMPOSE build auth-service chat-service ai-service connector-service
  ok "images rebuilt"
fi

# ------------------------------------------------------------------- boot
step "Starting containers"
$COMPOSE up -d
ok "compose up"

# ------------------------------------------------- wait for health + repair
# `ai.requests` is declared with a 30s TTL + DLX. A queue left behind by an
# older build without those arguments makes ai-service fail QueueDeclare with
# 406 PRECONDITION_FAILED and crash-loop forever. The queue is a job queue, so
# dropping it is safe: delete it and let the current code redeclare it.
fix_ai_queue() {
  local args
  args="$(docker exec chat-rabbitmq rabbitmqctl list_queues name arguments 2>/dev/null \
          | awk '$1 == "ai.requests" { $1=""; print }' || true)"
  if [ -n "$args" ] && ! printf '%s' "$args" | grep -q 'x-message-ttl'; then
    warn "ai.requests exists without x-message-ttl (stale) — recreating"
    docker exec chat-rabbitmq rabbitmqctl delete_queue ai.requests >/dev/null 2>&1 || true
    docker restart ai-service >/dev/null
    ok "ai-service restarted"
  fi
}

wait_http() {
  local name=$1 url=$2 want=$3 tries=${4:-60} code
  printf '  waiting for %-18s' "$name"
  for _ in $(seq 1 "$tries"); do
    code="$(curl -s -o /dev/null -w '%{http_code}' --max-time 3 "$url" || true)"
    case " $want " in *" $code "*) printf ' \033[32m%s\033[0m\n' "$code"; return 0 ;; esac
    printf '.'
    sleep 2
  done
  printf ' \033[31mtimeout (last=%s)\033[0m\n' "$code"
  return 1
}

step "Waiting for services"
wait_http auth-service      http://localhost:3001/health           200      || die "auth-service never came up — docker logs auth-service"
wait_http connector-service http://localhost:3003/health           200      || warn "connector-service not responding (MCP/skills off)"
# Actuator is secured, so 401 means Spring booted and is serving.
wait_http chat-service      http://localhost:8080/actuator/health  "200 401" 90 \
  || die "chat-service never came up — docker logs chat-service (ALLOWED_ORIGINS / Mongo?)"
sleep 3
fix_ai_queue
wait_http ai-service        http://localhost:3002/health           200      || warn "ai-service not responding — docker logs ai-service"

# ------------------------------------------------------------ realtime check
# Sending a message goes over REST, receiving one goes over the WebSocket. So a
# dead socket does not fail anything you can see: messages still send, they just
# never arrive until you reload. That is how a missing NEXT_PUBLIC_WS_URL passed
# for "the local backend has no realtime". Check the handshake directly instead.
check_realtime() {
  local code nonce
  # RFC 6455 §1.3's example nonce, quoted verbatim from the spec. It is a
  # constant every WebSocket implementation ships, not a credential — gitleaks
  # reads any base64 blob next to the word "Key" as a generic-api-key, which has
  # failed CI on this branch since the check was added.
  nonce='dGhlIHNhbXBsZSBub25jZQ==' # gitleaks:allow
  code="$(curl -s -o /dev/null -w '%{http_code}' --max-time 4 \
    -H 'Connection: Upgrade' -H 'Upgrade: websocket' -H 'Sec-WebSocket-Version: 13' \
    -H "Sec-WebSocket-Key: $nonce" \
    -H 'Origin: http://localhost:3000' http://localhost:8080/ws || true)"
  case "$code" in
    101) ok "websocket handshake 101 (realtime will work)" ;;
    403) die "chat-service rejected the handshake from http://localhost:3000 (403).
      ALLOWED_ORIGINS must include it — check infra/docker-compose/compose.yml." ;;
    *)   die "websocket handshake to :8080/ws returned '$code', expected 101.
      Without it the web app sends fine over REST but receives nothing." ;;
  esac
  # The browser is what actually has to reach the socket, and it uses this var.
  # Unset, the client derives ws://localhost:3000/ws — the Next dev server, which
  # never answers the upgrade.
  local envfile="$ROOT/apps/web/.env.development.local"
  if ! grep -q '^NEXT_PUBLIC_WS_URL=ws://localhost:8080/ws$' "$envfile" 2>/dev/null; then
    die "apps/web/.env.development.local is missing NEXT_PUBLIC_WS_URL=ws://localhost:8080/ws
      — the web app would open a socket to the Next dev server instead. Delete the
      file and re-run to regenerate it."
  fi
  ok "web points at the local websocket"
}
step "Checking realtime"
check_realtime

# ------------------------------------------------------------------- seed
if [ "$DO_SEED" = 1 ]; then
  step "Seeding fake test data"
  node "$ROOT/scripts/dev/seed-users.js"
  # --eval with the whole file, NOT `< file`: piping into stdin puts mongosh in
  # REPL mode, where it evaluates line by line — multi-line statements get split
  # ("Invalid REPL keyword" / "oldConvs.map is not a function") and the
  # clean-slate delete silently never runs, so re-seeding duplicates everything.
  docker exec -i chat-mongo mongosh platform --quiet \
    --eval "$(cat "$ROOT/scripts/dev/seed-chat.js")"
  ok "seeded"
fi

# -------------------------------------------------------------------- web
if [ "$DO_WEB" = 1 ]; then
  step "Starting Next.js dev server"
  if curl -s -o /dev/null --max-time 3 http://localhost:3000/login; then
    ok "already running on :3000"
  else
    mkdir -p "$ROOT/.dev-logs"
    (cd "$ROOT" && pnpm web >"$ROOT/.dev-logs/web.log" 2>&1 &)
    wait_http web http://localhost:3000/login "200 307" 45 \
      || warn "web didn't answer — tail .dev-logs/web.log"
  fi
fi

# ----------------------------------------------------------------- flutter
LAN_IP="$(ipconfig getifaddr en0 2>/dev/null || ipconfig getifaddr en1 2>/dev/null || true)"

MDNS_HOST="$(scutil --get LocalHostName 2>/dev/null || true)"

# A simulator shares the Mac's loopback, so localhost is correct and never goes
# stale — pin the URLs outright.
defines_for() {
  local host=$1
  printf '%s' "--dart-define=PON_AUTH_URL=http://$host:3001 \
--dart-define=PON_CHAT_URL=http://$host:8080 \
--dart-define=PON_AI_URL=http://$host:3002 \
--dart-define=PON_CONNECTOR_URL=http://$host:3003 \
--dart-define=PON_WS_URL=ws://$host:8080/ws"
}

# A physical phone has to come in over the LAN, and the Mac's LAN IP is a DHCP
# lease: it changes when you move between home, the office and a hotspot, which
# would strand a build made at the previous desk. So rather than pinning URLs,
# hand the app a hint plus the Bonjour name and let DevHostDiscovery re-resolve
# the host on every launch — including a sweep of the phone's own subnet, which
# works on a network neither machine has seen before. See
# apps/client/lib/core/config/dev_host_discovery.dart.
phone_defines_for() {
  local host=$1
  printf '%s' "--dart-define=PON_DEV_DISCOVERY=true \
--dart-define=PON_DEV_HOST=$host \
--dart-define=PON_DEV_MDNS=${MDNS_HOST:-unknown}.local"
}
read -r -a DEFINES <<<"$(defines_for localhost)"
read -r -a PHONE_DEFINES <<<"$(phone_defines_for "${LAN_IP:-<your-lan-ip>}")"

step "Ready"
cat <<EOF
  web            http://localhost:3000        (log: .dev-logs/web.log)
  auth  :3001    chat  :8080    ai  :3002    connector :3003
  mongo :27018   redis :6379    rabbit :5672 (UI :15672 platform/platform)

  test accounts  dev@pon.local / alice@pon.local / bob@pon.local
                 password: Devpass123!   (only exist after --seed)

  flutter on a real phone (lightest — no simulator on the Mac):
    ./scripts/dev/up.sh --phone
  or by hand:
    cd apps/client && flutter run -d <device> \\
      ${PHONE_DEFINES[*]}

  flutter on the simulator:
    cd apps/client && flutter run -d "$SIMULATOR" \\
      ${DEFINES[*]}

  stop everything:  $COMPOSE down
EOF

if [ "$DO_PHONE" = 1 ]; then
  step "Launching Flutter on a physical device"
  # The LAN IP is only a hint now — the app re-resolves the host at startup and
  # can find the Mac by sweeping the subnet even with no hint at all — so a
  # missing one is a warning, not a reason to stop.
  [ -n "$LAN_IP" ] || warn "couldn't read the Mac's LAN IP (en0/en1) — the app will fall back to discovery"
  # Pick the first real (non-emulator) mobile device flutter can see.
  phone_json="$(cd "$ROOT/apps/client" && flutter devices --machine 2>/dev/null)"
  phone_id="$(printf '%s' "$phone_json" | node -e '
    let s = "";
    process.stdin.on("data", (d) => (s += d)).on("end", () => {
      let list = [];
      try { list = JSON.parse(s); } catch { process.exit(0); }
      // Skips simulators/emulators (emulator: true) and the macOS/Chrome
      // targets (targetPlatform darwin / web-javascript).
      const d = list.find(
        (x) => !x.emulator && ["ios", "android"].includes(x.targetPlatform?.split("-")[0]),
      );
      if (d) console.log(`${d.id}\t${d.name}`);
    });
  ')"
  [ -n "$phone_id" ] || die "no physical phone found — plug it in (or enable wireless debugging) and check: flutter devices"
  printf '  device:  %s\n  backend: %s (hint) / %s — re-resolved at every launch\n  the phone still has to be on the same network as this Mac\n' \
    "$(printf '%s' "$phone_id" | cut -f2)" "${LAN_IP:-none}" "${MDNS_HOST:-unknown}.local"
  cd "$ROOT/apps/client" \
    && exec flutter run -d "$(printf '%s' "$phone_id" | cut -f1)" "${PHONE_DEFINES[@]}"
fi

if [ "$DO_FLUTTER" = 1 ]; then
  step "Launching Flutter on $SIMULATOR"
  udid="$(xcrun simctl list devices available 2>/dev/null \
          | grep -F "$SIMULATOR (" | head -1 | sed -E 's/.*\(([0-9A-F-]{36})\).*/\1/')"
  [ -n "$udid" ] || die "simulator \"$SIMULATOR\" not found — xcrun simctl list devices available"
  xcrun simctl bootstatus "$udid" -b >/dev/null 2>&1 || xcrun simctl boot "$udid" >/dev/null 2>&1 || true
  xcrun simctl bootstatus "$udid" -b >/dev/null 2>&1 || true
  open -a Simulator
  cd "$ROOT/apps/client" && exec flutter run -d "$udid" "${DEFINES[@]}"
fi
