import 'dart:async';

import 'package:audioplayers/audioplayers.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/services.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

/// Call tones in `assets/sounds/` (generated by tool/gen_call_tones.py).
enum CallTone { ringtone, ringback }

/// Plays a looping tone. Abstracted so [CallSounds] is testable without the
/// audio platform channel.
abstract class TonePlayer {
  Future<void> loop(CallTone tone, {bool speaker = false});
  Future<void> stop();
}

/// The audio session a tone plays in. audioplayers applies it app-wide
/// (Android `AudioManager.mode`, the iOS `AVAudioSession` category), so:
/// - the ringtone (before any call) obeys the iPhone silent switch;
/// - the ringback plays while WebRTC already holds the mic, so it must join
///   the voice-call session (in-communication mode, play-and-record with
///   Bluetooth) — a media context would flip the whole call to MODE_NORMAL /
///   playback and break echo cancellation, routing and AirPods.
AudioContext audioContextFor(CallTone tone, {bool speaker = false}) {
  if (tone == CallTone.ringtone) {
    return AudioContextConfig(respectSilence: true).build();
  }
  return AudioContext(
    android: AudioContextAndroid(
      isSpeakerphoneOn: speaker,
      stayAwake: false,
      contentType: AndroidContentType.speech,
      usageType: AndroidUsageType.voiceCommunication,
      audioFocus: AndroidAudioFocus.none,
      audioMode: AndroidAudioMode.inCommunication,
    ),
    iOS: AudioContextIOS(
      category: AVAudioSessionCategory.playAndRecord,
      options: {
        AVAudioSessionOptions.allowBluetooth,
        AVAudioSessionOptions.allowBluetoothA2DP,
        if (speaker) AVAudioSessionOptions.defaultToSpeaker,
      },
    ),
  );
}

class AudioplayersTonePlayer implements TonePlayer {
  final AudioPlayer _player = AudioPlayer();
  CallTone? _last;

  @override
  Future<void> loop(CallTone tone, {bool speaker = false}) async {
    await _player.stop();
    await _player.setAudioContext(audioContextFor(tone, speaker: speaker));
    await _player.setReleaseMode(ReleaseMode.loop);
    _last = tone;
    await _player.play(AssetSource('sounds/${tone.name}.wav'));
  }

  @override
  Future<void> stop() async {
    await _player.stop();
    // iOS keeps the ringtone's silent-switch (ambient) category app-wide,
    // which would mute voice notes afterwards: restore audioplayers' default.
    // Not on Android, where the global call rewrites AudioManager.mode.
    if (_last == CallTone.ringtone &&
        defaultTargetPlatform == TargetPlatform.iOS) {
      await AudioPlayer.global.setAudioContext(AudioContextConfig().build());
    }
    _last = null;
  }
}

/// Ringtone (+ vibration) for the callee, ringback for the caller.
class CallSounds {
  CallSounds(
    this._player, {
    void Function()? vibrate,
    this.vibrateEvery = const Duration(milliseconds: 1500),
  }) : _vibrate = vibrate ?? HapticFeedback.vibrate;

  final TonePlayer _player;
  final void Function() _vibrate;
  final Duration vibrateEvery;
  CallTone? _current;
  Timer? _vibrateTimer;

  Future<void> play(CallTone tone, {bool speaker = false}) async {
    if (_current == tone) return;
    await stop();
    _current = tone;
    if (tone == CallTone.ringtone) {
      _vibrate();
      _vibrateTimer = Timer.periodic(vibrateEvery, (_) => _vibrate());
    }
    try {
      await _player.loop(tone, speaker: speaker);
      // stop() may have run while loop() was starting the player.
      if (_current != tone) await _player.stop();
    } catch (e) {
      debugPrint('call tone failed: $e');
    }
  }

  Future<void> stop() async {
    _vibrateTimer?.cancel();
    _vibrateTimer = null;
    if (_current == null) return;
    _current = null;
    try {
      await _player.stop();
    } catch (_) {
      // best-effort
    }
  }
}

final callSoundsProvider = Provider<CallSounds>((ref) {
  final sounds = CallSounds(AudioplayersTonePlayer());
  ref.onDispose(sounds.stop);
  return sounds;
});
