import 'dart:async';

import 'package:audioplayers/audioplayers.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/services.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

/// Call tones in `assets/sounds/` (generated by tool/gen_call_tones.py).
enum CallTone { ringtone, ringback }

/// Plays a looping tone. Abstracted so [CallSounds] is testable without the
/// audio platform channel.
abstract class TonePlayer {
  Future<void> loop(CallTone tone, {bool speaker = false});
  Future<void> stop();
}

class AudioplayersTonePlayer implements TonePlayer {
  final AudioPlayer _player = AudioPlayer();

  @override
  Future<void> loop(CallTone tone, {bool speaker = false}) async {
    await _player.stop();
    await _player.setAudioContext(tone == CallTone.ringtone
        // Ringtone obeys the iPhone silent switch (vibration still runs).
        ? AudioContextConfig(respectSilence: true).build()
        // Ringback plays while WebRTC holds the mic: mix, don't steal focus.
        : AudioContextConfig(
            route: speaker
                ? AudioContextConfigRoute.speaker
                : AudioContextConfigRoute.earpiece,
            focus: AudioContextConfigFocus.mixWithOthers,
          ).build());
    await _player.setReleaseMode(ReleaseMode.loop);
    await _player.play(AssetSource('sounds/${tone.name}.wav'));
  }

  @override
  Future<void> stop() => _player.stop();
}

/// Ringtone (+ vibration) for the callee, ringback for the caller.
class CallSounds {
  CallSounds(
    this._player, {
    void Function()? vibrate,
    this.vibrateEvery = const Duration(milliseconds: 1500),
  }) : _vibrate = vibrate ?? HapticFeedback.vibrate;

  final TonePlayer _player;
  final void Function() _vibrate;
  final Duration vibrateEvery;
  CallTone? _current;
  Timer? _vibrateTimer;

  Future<void> play(CallTone tone, {bool speaker = false}) async {
    if (_current == tone) return;
    await stop();
    _current = tone;
    if (tone == CallTone.ringtone) {
      _vibrate();
      _vibrateTimer = Timer.periodic(vibrateEvery, (_) => _vibrate());
    }
    try {
      await _player.loop(tone, speaker: speaker);
      // stop() may have run while loop() was starting the player.
      if (_current != tone) await _player.stop();
    } catch (e) {
      debugPrint('call tone failed: $e');
    }
  }

  Future<void> stop() async {
    _vibrateTimer?.cancel();
    _vibrateTimer = null;
    if (_current == null) return;
    _current = null;
    try {
      await _player.stop();
    } catch (_) {
      // best-effort
    }
  }
}

final callSoundsProvider = Provider<CallSounds>((ref) {
  final sounds = CallSounds(AudioplayersTonePlayer());
  ref.onDispose(sounds.stop);
  return sounds;
});
